language: python
python:
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: coverage run --source=tests --include=rpn.py -m unittest discover -s tests/
after_success:
  - coveralls
