language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install coveralls
  - sudo pip install pyyaml
  - sudo pip install termcolor
# command to run tests
script: coverage run -m unittest discover -s tests/
after_success:
  coveralls
